name: Continuous Integration

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: List installed packages
      run: pip list
    - name: Test query_log_tracer package installation
      run: python -c 'import query_log_tracer'
    - name: Run command
      run: |
        query-log-tracer --log-file=./tests/files/general-query.log --target-table=dtb_customer --target-column=point --filter-column=id --filter-value=1

    - name: Install test dependencies
      run: |
        pip install ".[dev]"
    - name: List installed test packages
      run: pip list
    - name: Run unit tests
      run: |
        pytest --verbose
